Controllers/SittingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using ReservationSystem.Models;
using ReservationSystem.ViewModels;
using Newtonsoft.Json;

namespace ReservationSystem.Controllers
{
    public class SittingController : Controller
    {
        private readonly ISittingRepository _sittingRepository;
        private readonly ApplicationDbContext context;

        public SittingController(ISittingRepository sittingRepository, ApplicationDbContext context)
        {
            _sittingRepository = sittingRepository;
            this.context = context;

        }
        //sitting
        [HttpGet]
        public IActionResult AddSitting()
        {
            ViewBag.SittingTypes = context.SittingTypes.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddSitting(Sitting sitting)
        {
            var a = _sittingRepository.GetSittingWithType().Where(e=>e.SittingTypeId == sitting.SittingTypeId).FirstOrDefault();
           
            //validate the time is not within in the existing list 


               var validateDate = _sittingRepository.ValidateDate(sitting);
                if (sitting.Start < sitting.End && sitting.Start< DateTime.Now.AddDays(90))
                {
                    if (validateDate)
                    {
                        _sittingRepository.AddSitting(sitting);
                        return RedirectToAction("SittingList");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "These Time already exists. Please choose another time.";
                        ViewBag.SittingTypes = context.SittingTypes.ToList();
                        return View(sitting);
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Sorry,Start Time must be before End Time or schedule must be within 90 days. Please choose another time.";
                    ViewBag.SittingTypes = context.SittingTypes.ToList();
                    return View(sitting);
                }                
            
                         
        }

        public IActionResult Detail(int id)
        {

            Sitting model = _sittingRepository.GetSitting(id);
            return View(model);
        }
        public  IActionResult SittingList(string searchString)

        { 

            var sittings =  _sittingRepository.GetSittingWithType().ToList();

            if (!String.IsNullOrEmpty(searchString))
            {

                sittings = sittings.Where(s => s.SittingType.Description.Contains(searchString) || s.Start.ToShortDateString().Contains(searchString)||s.Capacity.ToString().Contains(searchString)).ToList();
            }
            return View(sittings);
        }
        [HttpPost]
        public IActionResult DeleteSelectedItems([FromBody]string[] SittingIds)
        {

            var sittings = _sittingRepository.GetSittingWithType().ToList();

                
            foreach(var id in SittingIds)
            {
                var s = sittings.Find(x=>x.SittingId == int.Parse(id));
                context.Sittings.Remove(s);
                
            }
            context.SaveChanges();
            return Json("All selected sittings deleted successfully!");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.SittingTypes = context.SittingTypes.ToList();
            var model = _sittingRepository.GetSitting(id);
            return View(model);         
        }
        [HttpPost]
        public RedirectToActionResult Edit(Sitting sitting)
        {
            Sitting updatedSitting = _sittingRepository.Update(sitting);
            return RedirectToAction("Detail", new { id = updatedSitting.SittingId });
        }
        [HttpPost]
        public RedirectToActionResult Delete(int id)
        {
            var model = _sittingRepository.GetSittingWithType().Where(e => e.SittingId == id).FirstOrDefault();
            var type = model.SittingType.Description;
            context.Sittings.Remove(model);
            context.SaveChanges();
            return RedirectToAction("SittingList", new { id = type });
        }

        //Sitting type
        public IActionResult SittingTypeList()
        {
            List<SittingType> sittingTypes = context.SittingTypes.ToList();
            return View(sittingTypes);
        }
        [HttpGet]
        public IActionResult AddSittingType()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSittingType(SittingType sittingType)
        {
           
            context.SittingTypes.Add(sittingType);
            context.SaveChanges();
            return RedirectToAction("DetailType", new { id = sittingType.Id });
        }
        [HttpGet]
        public IActionResult DeleteType(int id)
        {
            var model = context.SittingTypes.Find(id);
            return View(model);
        }
        [HttpPost]
        public RedirectToActionResult DeleteType(SittingType sittingType)
        {
            context.SittingTypes.Remove(sittingType);
            context.SaveChanges();
            return RedirectToAction("SittingTypeList");
        }
        [HttpGet]
        public IActionResult EditType(int id)
        {
            var model = context.SittingTypes.Find(id);
            return View(model);
        }
        [HttpPost]
        public RedirectToActionResult EditType(SittingType sittingType)
        {
            var _sittingType = context.SittingTypes.Attach(sittingType);
            _sittingType.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("DetailType", new { id = sittingType.Id });
        }
        public IActionResult DetailType(int id)
        {

            var model = context.SittingTypes.Find(id);
            return View(model);
        }
        [HttpGet]
        public JsonResult Test()
        {

            var data = context.Sittings.ToList();
          
            return Json(data);
            
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/client.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/login.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="#"><img src="~/picture/logo.png" class="logo" /></a>
            <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a asp-area="home" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @*<li class="nav-item">
            <a asp-area="Admin" asp-controller="admin" asp-action="CreateRole">Admin</a>
        </li>*@

                    @if (User.IsInRole("Staff"))
                    {
                        <li class="nav-item">
                            <div class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reservations</a>
                                <div class="dropdown-menu">
                                    <a asp-area="management" asp-controller="Reservation" asp-action="Create" class="dropdown-item text-warning">Make Reservations</a>
                                    <a asp-area="management" asp-controller="Reservation" asp-action="Index" class="dropdown-item text-warning">Check Reservations</a>
                                </div>
                            </div>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <div class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reservation</a>
                                <div class="dropdown-menu">
                                    <a asp-area="admin" asp-controller="Reservation" asp-action="Create" class="dropdown-item text-warning">Make Reservations</a>
                                    <a asp-area="admin" asp-controller="Reservation" asp-action="ReservationIndex" class="dropdown-item text-warning">Check Reservations</a>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage Sitting</a>
                                <div class="dropdown-menu">
                                    <a asp-area="" asp-controller="Sitting" asp-action="SittingList" class="dropdown-item text-warning">Sitting</a>
                                    <a asp-area="" asp-controller="Sitting" asp-action="SittingTypeList" class="dropdown-item text-warning">SittingType</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Admin" asp-action="RoleIndex">Admin</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="booking">Reservation</a>
                        </li>


                        <li class="nav-item">
                            <a asp-area="home" asp-controller="Home" asp-action="about">About</a>
                        </li>
                        @if (User.IsInRole("Member"))
                        {
                            <li class="nav-item">
                                <a asp-area="Member" asp-controller="home" asp-action="MyOrder">My Order</a>
                            </li>
                        }
                    }
                </ul>
                <partial name="_LoginPartial" />

            </div>
        </nav>
    </header>
    <div class="container-fluid main-body">
        <main role="main" >          
            @RenderBody()
        </main>
    </div>
    <footer id="contact">
        <div class="content">
            <div>
                <h3>Address</h3>
                <p>300 George St,Sydney 2000,Australia</p>
            </div>
            <div >
                <h3>Opening hours</h3>
                <p style="font-size:14px;">Mon-Sun: 8am-11am,11am-2pm,4pm-9pm</p>
            </div>
            <div>
                <h3>Contact</h3>
                <p>
                    <span>+421 000 000</span>
                    <br />
                    <span>BeanScene@gmail.com</span>
                </p>
            </div>
            <div>
                <h3>Follow</h3>
                <a href="https://www.facebook.com/"><i class="fa fa-facebook-official" style="font-size:30px;margin-left:10px"></i></a>
                <a href="https://www.instagram.com/">
                    <i class="fa fa-instagram" style="font-size:30px;margin-left:10px"></i>
                </a>
            </div>
        </div>
        <div class="rights">©2020 by BeanScene's Restaurant.</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>